// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvHeaderSpec) DeepCopyInto(out *EnvHeaderSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvHeaderSpec.
func (in *EnvHeaderSpec) DeepCopy() *EnvHeaderSpec {
	if in == nil {
		return nil
	}
	out := new(EnvHeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvLabelSpec) DeepCopyInto(out *EnvLabelSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvLabelSpec.
func (in *EnvLabelSpec) DeepCopy() *EnvLabelSpec {
	if in == nil {
		return nil
	}
	out := new(EnvLabelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualEnvironment) DeepCopyInto(out *VirtualEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualEnvironment.
func (in *VirtualEnvironment) DeepCopy() *VirtualEnvironment {
	if in == nil {
		return nil
	}
	out := new(VirtualEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualEnvironmentList) DeepCopyInto(out *VirtualEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualEnvironmentList.
func (in *VirtualEnvironmentList) DeepCopy() *VirtualEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(VirtualEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualEnvironmentSpec) DeepCopyInto(out *VirtualEnvironmentSpec) {
	*out = *in
	out.EnvLabel = in.EnvLabel
	out.EnvHeader = in.EnvHeader
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualEnvironmentSpec.
func (in *VirtualEnvironmentSpec) DeepCopy() *VirtualEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualEnvironmentStatus) DeepCopyInto(out *VirtualEnvironmentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualEnvironmentStatus.
func (in *VirtualEnvironmentStatus) DeepCopy() *VirtualEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}
